### PR TITLE
F/missingvalues2

### LINKED ISSUE #82: update isMongo facet to sort by checked:desc, count:desc
Right now checked values in a facet don't get any special treatment, and so don't show up at the top of the facet list unless the list is long enough to reach the position where they'd be if they weren't checked. This is a regression from something.

Need to add to https://github.com/smartprocure/contexture-mongo/blob/master/src/example-types/facet.js#L17 roughly like this:

```js
  { $addFields: { isSelected: <is in node.values> } },
  { $sort: { isSelected: -1, count: 1 } } 
```

to produce a sort by checked-ness first

### PR DESCRIPTION
**Pull request by chris110408**
Have to close PR #85, Becuase the problem 
image

fix #82

the mongo search may not include the checked values.
1.when no checked values are missing from the First search the search result is the result from first search
2. when there are missed values run the second search.
3. if the value still missing (not able to get the checked value from search) run the third search.
when 2 or 3 happens. the final result is the combination of 1st,2nd, and 3rd search

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please assign someone to merge this PR, and optionally include people who should review.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  Branch being merged does not follow [Git Flow](http://nvie.com/posts/a-successful-git-branching-model/)
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>You should add at least 1 more reviewer to the PR</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: 947fa50d37f296cc3975690021f21c90690be827


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d661ef6deaf4a6d692cd7aa2df457a6e26095095
</p>

File: src/example-types/facet.js [hunk 1]
```diff
@@ -134,5 +138,76 @@ module.exports = {
...
+          .getProvider(node)
+          .runSearch(
+            config.options,
+            node,
+            config.getSchema(node.schema),
+            stillMissingQueryFilter,
+            stillMissingArgs
+          )
+      }
+      let finalMissedReult = _.flow(
```
Comment (daedalus28) [inline src/example-types/facet.js:195]: `finalMissedReult` -> `finalMissedResult`

File: src/example-types/facet.js [hunk 2]
```diff
@@ -134,5 +138,76 @@ module.exports = {
...
+      )
+      let stillMissingQueryFilter = {
+        [node.field]: { $in: getMissedValues(node, stillMissingValues) },
+      }
+      let stillMissingArgs = [
+        { $group: { _id: `$${node.field}` } },
+        ...lookupLabel(node),
+        _.get('label.fields', node) && projectStageFromLabelFields(node),
+      ]
+      let stillmissingResult = []
```
Comment (daedalus28) [inline src/example-types/facet.js:182]: `stillmissingResult` -> `stillMssingResult`

File: src/example-types/facet.js (hunk 1 above)
Comment (daedalus28) [reply src/example-types/facet.js:195]: a lot of these names are really similar - I think you're better off just inlining a bunch of these so it's easier to follow

**Review by daedalus28 — CHANGES_REQUESTED** [review]

File: src/example-types/facet.js [hunk 3]
```diff
@@ -134,5 +138,75 @@ module.exports = {
...
+    let missedValues = _.difference(
+      values,
+      _.map(
+        ({ name }) => (node.isMongoId ? _.toString(name) : name),
+        results.options
+      )
+    )
+
+    let getMissedValues = (node, missedValues) =>
+      node.isMongoId ? _.map(ObjectID, missedValues) : missedValues
```
Comment (daedalus28) [inline src/example-types/facet.js:152]: `getMissedValues` isn't what this does - it's really a `maybeMapObjectId`. Since `node` is already in scope here, you can simplify to something like this:

```js
let maybeMapObjectId = F.when(node.isMongoId, _.map(ObjectId))
```

File: src/example-types/facet.js [hunk 4]
```diff
@@ -134,5 +138,75 @@ module.exports = {
...
+          mapKeywordFilters(node),
+        ])
+      )
+      // the value will be missing. when the value has been checked but not in the search result we return it with count 0
+      let checkedButNotInSearchValues = _.difference(
+        //when values are numeric values, stringify missedValues to avoid the bug.
+        _.map(_.toString, missedValues),
+        _.map(x => _.toString(x[`${node.field}`]), searchMissedResult)
+      )
+      let checkedButNotInSearchResult = []
```
Comment (daedalus28) [inline src/example-types/facet.js]: these are some really verbose names 🤔

**Review by daedalus28 — CHANGES_REQUESTED** [review]

File: src/example-types/facet.js [hunk 5]
```diff
@@ -134,5 +138,73 @@ module.exports = {
...
+        ({ name }) => (node.isMongoId ? _.toString(name) : name),
+        results.options
+      )
+    )
+
+    let getMissedValues = (node, missedValues) =>
+      node.isMongoId ? _.map(ObjectID, missedValues) : missedValues
+
+    if (!_.isEmpty(missedValues)) {
+      let MissedResult = await search(
```
Comment (daedalus28) [inline src/example-types/facet.js:155]: we don't capitalize instance variable names :)

File: src/example-types/facet.js [hunk 6]
```diff
@@ -134,5 +138,73 @@ module.exports = {
...
+        _.map(x => _.toString(x[`${node.field}`]), MissedResult)
+      )
+      let missedByFilterResult = []
+
+      if (!_.isEmpty(missedByFilterValues)) {
+        //use config to run runSearch(options, node, schema, filters, aggs)  function
+        missedByFilterResult = await config.getProvider(node).runSearch(
+          config.options,
+          node,
+          config.getSchema(node.schema),
```
Comment (daedalus28) [inline src/example-types/facet.js:182]: I think it's worth factoring out a util like this at the top level:

```js
let runSearch = ({ options, getSchema, getProvider }, node) => (filters, aggs) =>
  getProvider(node).runSearch(options, node, getSchema(node.schema), filters, aggs)
```

to clearly separate out this bit of contexture trivia from the details of `facet`

Comment (daedalus28) [reply src/example-types/facet.js:182]: long term, we'd add a curried search without filters or something to the core

File: src/example-types/facet.js [hunk 7]
```diff
@@ -134,5 +138,73 @@ module.exports = {
           }),
         options
       ),
-    })),
+    }))
+
+    let missedValues = _.difference(
+      values,
+      _.map(
+        ({ name }) => (node.isMongoId ? _.toString(name) : name),
```
Comment (daedalus28) [inline src/example-types/facet.js:146]: this might clean stuff up:

```js
F.when(node.isMongoId, _.toString, name)
```

up to you though, it might also be worse

File: src/example-types/facet.js [hunk 8]
```diff
@@ -134,5 +138,73 @@ module.exports = {
...
+
+      let missedValuesOptions = _.map(
+        ({ _id, label, count }) => ({
+          name: _id,
+          count,
+          ...facetValueLabel(node, label),
+        }),
+        _.flow(
+          _.map(({ _id, label }) => ({ _id, label, count: 0 })),
+          _.concat(MissedResult)
```
Comment (daedalus28) [inline src/example-types/facet.js:202]: I think it might be simpler if you just concat in one step at the end instead of here and also below - better separation of concerns that way

Comment (chris110408) [reply src/example-types/facet.js]: I moved the _.map(({ _id, label }) => ({ _id, label, count: 0 })), to the previous function.

File: src/example-types/facet.js [hunk 9]
```diff
@@ -77,42 +97,38 @@ let unwindPropOrField = node =>
     _.castArray(node.unwind || node.field)
   )
 
+let runSearch = ({ options, getSchema, getProvider }, node) => (
```
Comment (chris110408) [inline src/example-types/facet.js:100]: separate runSearch function from the result function to this line

File: src/example-types/facet.js [hunk 10]
```diff
@@ -134,5 +150,64 @@ module.exports = {
...
+    let lostIds = _.difference(
+      valueIds,
+      _.map(
+        ({ name }) => F.when(node.isMongoId, _.toString, name),
+        results.options
+      )
+    )
+
+    let maybeMapObjectId = missedIds =>
+      node.isMongoId ? _.map(ObjectId, missedIds) : missedIds
```
Comment (chris110408) [inline src/example-types/facet.js:164]: Have to use if else in this way, Cause if there is no isMongoId attribute in node.isMongoId is undefined. we have condition undefined bug when we use F.when

**Review by daedalus28 — APPROVED** [review]
