### PR TITLE
Should not filter 0 value

### LINKED ISSUE #108: facet response incorrectly remove the 0 value
Contexture-mongo will incorrectly remove the 0 value from options, by treating  0 value as a falsey value.

### PR DESCRIPTION
**Pull request by chris110408**
fixes #108

 fix the bug the response of facet remove the 0 value name option ( `compactObject` consider it as a false value ).
switch the `compactObject`  to omitNil

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please assign someone to merge this PR, and optionally include people who should review.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  Branch being merged does not follow [Git Flow](http://nvie.com/posts/a-successful-git-branching-model/)
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>You should add at least 1 more reviewer to the PR</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: 40b4f1211ed702ba7a574a00c0171e9affe36160


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2084c8324b22778a56ed21aa2ebf9179c1c94cd5
</p>

**Review by daedalus28 — CHANGES_REQUESTED** [review]
Don't forget to add a test case

File: src/example-types/facet.js [hunk 1]
```diff
@@ -141,9 +141,9 @@ module.exports = {
       ]),
     ]).then(([options, cardinality]) => ({
       cardinality: _.get('0.count', cardinality),
-      options: _.map(
+      options: console.log(options)||_.map(
```
Comment (chris110408) [inline src/example-types/facet.js:144]: the result I get is [ { _id: 1, count: 1 } ]

**Comment by chris110408** [comment]
> Don't forget to add a test case
We are not able to get the expect result by using mingo. Because of the bug https://github.com/kofrasa/mingo/issues/166
I have submitted a fix for it  https://github.com/kofrasa/mingo/pull/165. let us merge the PR now. I will create a unit test as a follow-up PR.

**Review by daedalus28 — APPROVED** [review]
Nice work!
