### PR TITLE
feature/71 - fix dateHistogram and test

### LINKED ISSUE #71: correct dateHistogram cardinality prop
My judgment as to what the `cardinality` prop on a dateHistogram was intended to count was mistaken on #68 -- the prop should hold a count of unique values. Need to update the code and test to implement that properly.

### PR DESCRIPTION
**Pull request by doug-patterson**
Fixes #71 

### Description
* original implementation for dateHistogram had tests that didn't pass for several reasons.
  * also counted unique values rather than unique keys, which to me looks wrong
* work here implements cardinality as a count of unique keys contributing a value during an interval
* also restores testing timezone sensitive props of the returned data
  * timezone offset needs to be doubled because mingo isn't timezone aware so you need to account for two lost offsets from `new Date()` in the course of the tests - once when you make the data and again when mingo "reads" it.

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please assign someone to merge this PR, and optionally include people who should review.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>This PR has failing tests. Please alleviate the errors and commit them

<details>
  <summary>result should output the expected query and results</summary>
  <code>expected { Object (entries) } to deeply equal { Object (entries) }</code>
</details></td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>The changelog has not been updated. Please update the changelog.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>The version was not updated. Please update the version.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against faab33a01c2f8656948adf54df7e065c37846d28
</p>

**Comment by doug-patterson** [comment]
@daedalus28 I've put it back the way it was. Note the test fails. I'm really having trouble figuring out what you were trying to accomplish -- the `$sum` in the `$project` isn't behaving as the restored code seems to expect it to. Any ideas?

**Comment by doug-patterson** [comment]
At least it counts something sensible now, but tests are still producing this inexplicable fail, as thoug { $size } is not getting projected: 

```
d results:

      AssertionError: expected { Object (entries) } to deeply equal { Object (entries) }
      + expected - actual

       {
         "entries": [
           {
             "avg": 2250
      -      "cardinality": [
      -        {}
      -      ]
      +      "cardinality": 10
             "count": 10
             "max": 4500
             "min": 0
             "sum": 22500
           }
           {
             "avg": 2350
      -      "cardinality": [
      -        {}
      -      ]
      +      "cardinality": 10
             "count": 10
             "max": 4600
             "min": 100
             "sum": 23500
           }
           {
             "avg": 2450
      -      "cardinality": [
      -        {}
      -      ]
      +      "cardinality": 10
             "count": 10
             "max": 4700
             "min": 200
             "sum": 24500
           }
           {
             "avg": 2550
      -      "cardinality": [
      -        {}
      -      ]
      +      "cardinality": 10
             "count": 10
             "max": 4800
             "min": 300
             "sum": 25500
           }
           {
             "avg": 2650
      -      "cardinality": [
      -        {}
      -      ]
      +      "cardinality": 10
             "count": 10
             "max": 4900
             "min": 400
             "sum": 26500
      

```

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `/home/circleci/project/node_modules/duti/src/dangerfile.js`.
  </td>
    </tr>
  </tbody>
</table>



## Error Error
```
[
  {
    "$group": {
      "_id": {
        "day": {
          "$dayOfMonth": "$createdAt"
        },
        "month": {
          "$month": "$createdAt"
        },
        "year": {
          "$year": "$createdAt"
        }
      },
      "min": {
        "$min": "$metrics.usersCount"
      },
      "max": {
        "$max": "$metrics.usersCount"
      },
      "avg": {
        "$avg": "$metrics.usersCount"
      },
      "sum": {
        "$sum": "$metrics.usersCount"
      },
      "count": {
        "$sum": 1
      },
      "cardinality": {
        "$addToSet": "$createdAt"
      }
    }
  },
  {
    "$project": {
      "day": "$_id.day",
      "month": "$_id.month",
      "year": "$_id.year",
      "_id": 0,
      "min": 1,
      "max": 1,
      "avg": 1,
      "sum": 1,
      "count": 1,
      "cardinality": {
        "$size": "$cardinality"
      }
    }
  },
  {
    "$sort": {
      "year": 1,
      "month": 1,
      "day": 1
    }
  }
]
{
  "stats": {
    "suites": 29,
    "tests": 53,
    "passes": 53,
    "pending": 0,
    "failures": 0,
    "start": "2020-03-24T20:55:42.823Z",
    "end": "2020-03-24T20:55:42.866Z",
    "duration": 43
  },
  "tests": [
    {
      "title": "should check for values",
      "fullTitle": "date date.hasValue should check for values",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "basic",
      "fullTitle": "date date.filter basic",
      "duration": 3,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "basic datemath",
      "fullTitle": "date date.filter basic datemath",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "ms timestamp",
      "fullTitle": "date date.filter ms timestamp",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "unix timestamp",
      "fullTitle": "date date.filter unix timestamp",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should output the expected query and results",
      "fullTitle": "dateHistogram dateHistogram.result result should output the expected query and results",
      "duration": 11,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "If a value is provided, use $and",
      "fullTitle": "exists exists.filter If a value is provided, use $and",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "If no value is provided, use $or",
      "fullTitle": "exists exists.filter If no value is provided, use $or",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should allow nodes with values",
      "fullTitle": "facet facet.hasValue Should allow nodes with values",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should not allow nodes with values",
      "fullTitle": "facet facet.hasValue Should not allow nodes with values",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should call the search function and wait for it",
      "fullTitle": "facet facet.result should call the search function and wait for it",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should default the limit query to 10 if size is not provided",
      "fullTitle": "facet facet.result should default the limit query to 10 if size is not provided",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should allow unlimited queries",
      "fullTitle": "facet facet.result should allow unlimited queries",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should support optionsFilter",
      "fullTitle": "facet facet.result should support optionsFilter",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should support optionsFilter with multiple words and spaces",
      "fullTitle": "facet facet.result should support optionsFilter with multiple words and spaces",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should support isMongoId",
      "fullTitle": "facet facet.result should support isMongoId",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should check for value",
      "fullTitle": "mongoId mongoId.hasValue should check for value",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should create filter for _id",
      "fullTitle": "mongoId mongoId.filter should create filter for _id",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should handle $in with a data.values array",
      "fullTitle": "mongoId mongoId.filter should handle $in with a data.values array",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should handle $in with a data.values array",
      "fullTitle": "mongoId mongoId.filter should handle $in with a data.values array",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Allows optionally either min or max",
      "fullTitle": "number number.hasValue Allows optionally either min or max",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Allows 0 on min and max",
      "fullTitle": "number number.hasValue Allows 0 on min and max",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should reject empty string, null, undefined, Infinity, and NaN",
      "fullTitle": "number number.hasValue Should reject empty string, null, undefined, Infinity, and NaN",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should handle numbers as strings",
      "fullTitle": "number number.hasValue Should handle numbers as strings",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should convert both min and max to valid numbers",
      "fullTitle": "number number.filter Should convert both min and max to valid numbers",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should remove unused properties",
      "fullTitle": "number number.filter Should remove unused properties",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should remove fields if not valid",
      "fullTitle": "number number.filter Should remove fields if not valid",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should translate populate object into an array of $lookup objects",
      "fullTitle": "results convertPopulate should translate populate object into an array of $lookup objects",
      "duration": 6,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should add \"$unwind\" stage if \"unwind\" is present in the populate config",
      "fullTitle": "results convertPopulate should add \"$unwind\" stage if \"unwind\" is present in the populate config",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should return 0 if page is 1",
      "fullTitle": "results getStartRecord should return 0 if page is 1",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should return 0 if page is < 1",
      "fullTitle": "results getStartRecord should return 0 if page is < 1",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should return 10 if page is 2",
      "fullTitle": "results getStartRecord should return 10 if page is 2",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should put $sort, $skip, $limit first in pipeline",
      "fullTitle": "results getResultsQuery should put $sort, $skip, $limit first in pipeline",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should put $sort, $skip, $limit first in pipeline where sort field is not part of a join",
      "fullTitle": "results getResultsQuery should put $sort, $skip, $limit first in pipeline where sort field is not part of a join",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should put $sort, $skip, $limit first after $lookup",
      "fullTitle": "results getResultsQuery should put $sort, $skip, $limit first after $lookup",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should sort descending and skip $lookup and $project",
      "fullTitle": "results getResultsQuery should sort descending and skip $lookup and $project",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should not have $limit stage if pageSize is 0",
      "fullTitle": "results getResultsQuery should not have $limit stage if pageSize is 0",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should not have $sort stage if sortField is missing",
      "fullTitle": "results getResultsQuery should not have $sort stage if sortField is missing",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should fetch an extra item if skipCount is true",
      "fullTitle": "results getResultsQuery should fetch an extra item if skipCount is true",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should remove redundant child paths",
      "fullTitle": "results projectFromInclude should remove redundant child paths",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should only set hasMore if count is skipped",
      "fullTitle": "results getResponse should only set hasMore if count is skipped",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should set hasMore if there are extra results",
      "fullTitle": "results getResponse should set hasMore if there are extra results",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should not set hasMore if there are no extra results",
      "fullTitle": "results getResponse should not set hasMore if there are no extra results",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should set startRecord and endRecord based on the page",
      "fullTitle": "results getResponse should set startRecord and endRecord based on the page",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should set totalRecords based on the count (if it exists)",
      "fullTitle": "results getResponse should set totalRecords based on the count (if it exists)",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should output the expected query",
      "fullTitle": "statistical statistical.result result should output the expected query",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should handle no results",
      "fullTitle": "statistical statistical.result result should handle no results",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should output the expected query and results",
      "fullTitle": "termsStats termsStats.result result should output the expected query and results",
      "duration": 2,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect a value",
      "fullTitle": "text text.hasValue should detect a value",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect if values is empty",
      "fullTitle": "text text.hasValue should detect if values is empty",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect if values only contains an empty string",
      "fullTitle": "text text.hasValue should detect if values only contains an empty string",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect if value is the empty string",
      "fullTitle": "text text.hasValue should detect if value is the empty string",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should check for values",
      "fullTitle": "text text.filter should check for values",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    }
  ],
  "pending": [],
  "failures": [],
  "passes": [
    {
      "title": "should check for values",
      "fullTitle": "date date.hasValue should check for values",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "basic",
      "fullTitle": "date date.filter basic",
      "duration": 3,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "basic datemath",
      "fullTitle": "date date.filter basic datemath",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "ms timestamp",
      "fullTitle": "date date.filter ms timestamp",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "unix timestamp",
      "fullTitle": "date date.filter unix timestamp",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should output the expected query and results",
      "fullTitle": "dateHistogram dateHistogram.result result should output the expected query and results",
      "duration": 11,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "If a value is provided, use $and",
      "fullTitle": "exists exists.filter If a value is provided, use $and",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "If no value is provided, use $or",
      "fullTitle": "exists exists.filter If no value is provided, use $or",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should allow nodes with values",
      "fullTitle": "facet facet.hasValue Should allow nodes with values",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should not allow nodes with values",
      "fullTitle": "facet facet.hasValue Should not allow nodes with values",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should call the search function and wait for it",
      "fullTitle": "facet facet.result should call the search function and wait for it",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should default the limit query to 10 if size is not provided",
      "fullTitle": "facet facet.result should default the limit query to 10 if size is not provided",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should allow unlimited queries",
      "fullTitle": "facet facet.result should allow unlimited queries",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should support optionsFilter",
      "fullTitle": "facet facet.result should support optionsFilter",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should support optionsFilter with multiple words and spaces",
      "fullTitle": "facet facet.result should support optionsFilter with multiple words and spaces",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should support isMongoId",
      "fullTitle": "facet facet.result should support isMongoId",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should check for value",
      "fullTitle": "mongoId mongoId.hasValue should check for value",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should create filter for _id",
      "fullTitle": "mongoId mongoId.filter should create filter for _id",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should handle $in with a data.values array",
      "fullTitle": "mongoId mongoId.filter should handle $in with a data.values array",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should handle $in with a data.values array",
      "fullTitle": "mongoId mongoId.filter should handle $in with a data.values array",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Allows optionally either min or max",
      "fullTitle": "number number.hasValue Allows optionally either min or max",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Allows 0 on min and max",
      "fullTitle": "number number.hasValue Allows 0 on min and max",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should reject empty string, null, undefined, Infinity, and NaN",
      "fullTitle": "number number.hasValue Should reject empty string, null, undefined, Infinity, and NaN",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should handle numbers as strings",
      "fullTitle": "number number.hasValue Should handle numbers as strings",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should convert both min and max to valid numbers",
      "fullTitle": "number number.filter Should convert both min and max to valid numbers",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should remove unused properties",
      "fullTitle": "number number.filter Should remove unused properties",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should remove fields if not valid",
      "fullTitle": "number number.filter Should remove fields if not valid",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should translate populate object into an array of $lookup objects",
      "fullTitle": "results convertPopulate should translate populate object into an array of $lookup objects",
      "duration": 6,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should add \"$unwind\" stage if \"unwind\" is present in the populate config",
      "fullTitle": "results convertPopulate should add \"$unwind\" stage if \"unwind\" is present in the populate config",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should return 0 if page is 1",
      "fullTitle": "results getStartRecord should return 0 if page is 1",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should return 0 if page is < 1",
      "fullTitle": "results getStartRecord should return 0 if page is < 1",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should return 10 if page is 2",
      "fullTitle": "results getStartRecord should return 10 if page is 2",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should put $sort, $skip, $limit first in pipeline",
      "fullTitle": "results getResultsQuery should put $sort, $skip, $limit first in pipeline",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should put $sort, $skip, $limit first in pipeline where sort field is not part of a join",
      "fullTitle": "results getResultsQuery should put $sort, $skip, $limit first in pipeline where sort field is not part of a join",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should put $sort, $skip, $limit first after $lookup",
      "fullTitle": "results getResultsQuery should put $sort, $skip, $limit first after $lookup",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should sort descending and skip $lookup and $project",
      "fullTitle": "results getResultsQuery should sort descending and skip $lookup and $project",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should not have $limit stage if pageSize is 0",
      "fullTitle": "results getResultsQuery should not have $limit stage if pageSize is 0",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should not have $sort stage if sortField is missing",
      "fullTitle": "results getResultsQuery should not have $sort stage if sortField is missing",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should fetch an extra item if skipCount is true",
      "fullTitle": "results getResultsQuery should fetch an extra item if skipCount is true",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should remove redundant child paths",
      "fullTitle": "results projectFromInclude should remove redundant child paths",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should only set hasMore if count is skipped",
      "fullTitle": "results getResponse should only set hasMore if count is skipped",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should set hasMore if there are extra results",
      "fullTitle": "results getResponse should set hasMore if there are extra results",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should not set hasMore if there are no extra results",
      "fullTitle": "results getResponse should not set hasMore if there are no extra results",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should set startRecord and endRecord based on the page",
      "fullTitle": "results getResponse should set startRecord and endRecord based on the page",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should set totalRecords based on the count (if it exists)",
      "fullTitle": "results getResponse should set totalRecords based on the count (if it exists)",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should output the expected query",
      "fullTitle": "statistical statistical.result result should output the expected query",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should handle no results",
      "fullTitle": "statistical statistical.result result should handle no results",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should output the expected query and results",
      "fullTitle": "termsStats termsStats.result result should output the expected query and results",
      "duration": 2,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect a value",
      "fullTitle": "text text.hasValue should detect a value",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect if values is empty",
      "fullTitle": "text text.hasValue should detect if values is empty",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect if values only contains an empty string",
      "fullTitle": "text text.hasValue should detect if values only contains an empty string",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect if value is the empty string",
      "fullTitle": "text text.hasValue should detect if value is the empty string",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should check for values",
      "fullTitle": "text text.filter should check for values",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    }
  ]
}
Error: [
  {
    "$group": {
      "_id": {
        "day": {
          "$dayOfMonth": "$createdAt"
        },
        "month": {
          "$month": "$createdAt"
        },
        "year": {
          "$year": "$createdAt"
        }
      },
      "min": {
        "$min": "$metrics.usersCount"
      },
      "max": {
        "$max": "$metrics.usersCount"
      },
      "avg": {
        "$avg": "$metrics.usersCount"
      },
      "sum": {
        "$sum": "$metrics.usersCount"
      },
      "count": {
        "$sum": 1
      },
      "cardinality": {
        "$addToSet": "$createdAt"
      }
    }
  },
  {
    "$project": {
      "day": "$_id.day",
      "month": "$_id.month",
      "year": "$_id.year",
      "_id": 0,
      "min": 1,
      "max": 1,
      "avg": 1,
      "sum": 1,
      "count": 1,
      "cardinality": {
        "$size": "$cardinality"
      }
    }
  },
  {
    "$sort": {
      "year": 1,
      "month": 1,
      "day": 1
    }
  }
]
{
  "stats": {
    "suites": 29,
    "tests": 53,
    "passes": 53,
    "pending": 0,
    "failures": 0,
    "start": "2020-03-24T20:55:42.823Z",
    "end": "2020-03-24T20:55:42.866Z",
    "duration": 43
  },
  "tests": [
    {
      "title": "should check for values",
      "fullTitle": "date date.hasValue should check for values",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "basic",
      "fullTitle": "date date.filter basic",
      "duration": 3,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "basic datemath",
      "fullTitle": "date date.filter basic datemath",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "ms timestamp",
      "fullTitle": "date date.filter ms timestamp",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "unix timestamp",
      "fullTitle": "date date.filter unix timestamp",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should output the expected query and results",
      "fullTitle": "dateHistogram dateHistogram.result result should output the expected query and results",
      "duration": 11,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "If a value is provided, use $and",
      "fullTitle": "exists exists.filter If a value is provided, use $and",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "If no value is provided, use $or",
      "fullTitle": "exists exists.filter If no value is provided, use $or",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should allow nodes with values",
      "fullTitle": "facet facet.hasValue Should allow nodes with values",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should not allow nodes with values",
      "fullTitle": "facet facet.hasValue Should not allow nodes with values",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should call the search function and wait for it",
      "fullTitle": "facet facet.result should call the search function and wait for it",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should default the limit query to 10 if size is not provided",
      "fullTitle": "facet facet.result should default the limit query to 10 if size is not provided",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should allow unlimited queries",
      "fullTitle": "facet facet.result should allow unlimited queries",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should support optionsFilter",
      "fullTitle": "facet facet.result should support optionsFilter",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should support optionsFilter with multiple words and spaces",
      "fullTitle": "facet facet.result should support optionsFilter with multiple words and spaces",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should support isMongoId",
      "fullTitle": "facet facet.result should support isMongoId",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should check for value",
      "fullTitle": "mongoId mongoId.hasValue should check for value",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should create filter for _id",
      "fullTitle": "mongoId mongoId.filter should create filter for _id",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should handle $in with a data.values array",
      "fullTitle": "mongoId mongoId.filter should handle $in with a data.values array",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should handle $in with a data.values array",
      "fullTitle": "mongoId mongoId.filter should handle $in with a data.values array",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Allows optionally either min or max",
      "fullTitle": "number number.hasValue Allows optionally either min or max",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Allows 0 on min and max",
      "fullTitle": "number number.hasValue Allows 0 on min and max",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should reject empty string, null, undefined, Infinity, and NaN",
      "fullTitle": "number number.hasValue Should reject empty string, null, undefined, Infinity, and NaN",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should handle numbers as strings",
      "fullTitle": "number number.hasValue Should handle numbers as strings",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should convert both min and max to valid numbers",
      "fullTitle": "number number.filter Should convert both min and max to valid numbers",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should remove unused properties",
      "fullTitle": "number number.filter Should remove unused properties",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should remove fields if not valid",
      "fullTitle": "number number.filter Should remove fields if not valid",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should translate populate object into an array of $lookup objects",
      "fullTitle": "results convertPopulate should translate populate object into an array of $lookup objects",
      "duration": 6,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should add \"$unwind\" stage if \"unwind\" is present in the populate config",
      "fullTitle": "results convertPopulate should add \"$unwind\" stage if \"unwind\" is present in the populate config",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should return 0 if page is 1",
      "fullTitle": "results getStartRecord should return 0 if page is 1",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should return 0 if page is < 1",
      "fullTitle": "results getStartRecord should return 0 if page is < 1",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should return 10 if page is 2",
      "fullTitle": "results getStartRecord should return 10 if page is 2",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should put $sort, $skip, $limit first in pipeline",
      "fullTitle": "results getResultsQuery should put $sort, $skip, $limit first in pipeline",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should put $sort, $skip, $limit first in pipeline where sort field is not part of a join",
      "fullTitle": "results getResultsQuery should put $sort, $skip, $limit first in pipeline where sort field is not part of a join",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should put $sort, $skip, $limit first after $lookup",
      "fullTitle": "results getResultsQuery should put $sort, $skip, $limit first after $lookup",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should sort descending and skip $lookup and $project",
      "fullTitle": "results getResultsQuery should sort descending and skip $lookup and $project",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should not have $limit stage if pageSize is 0",
      "fullTitle": "results getResultsQuery should not have $limit stage if pageSize is 0",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should not have $sort stage if sortField is missing",
      "fullTitle": "results getResultsQuery should not have $sort stage if sortField is missing",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should fetch an extra item if skipCount is true",
      "fullTitle": "results getResultsQuery should fetch an extra item if skipCount is true",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should remove redundant child paths",
      "fullTitle": "results projectFromInclude should remove redundant child paths",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should only set hasMore if count is skipped",
      "fullTitle": "results getResponse should only set hasMore if count is skipped",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should set hasMore if there are extra results",
      "fullTitle": "results getResponse should set hasMore if there are extra results",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should not set hasMore if there are no extra results",
      "fullTitle": "results getResponse should not set hasMore if there are no extra results",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should set startRecord and endRecord based on the page",
      "fullTitle": "results getResponse should set startRecord and endRecord based on the page",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should set totalRecords based on the count (if it exists)",
      "fullTitle": "results getResponse should set totalRecords based on the count (if it exists)",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should output the expected query",
      "fullTitle": "statistical statistical.result result should output the expected query",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should handle no results",
      "fullTitle": "statistical statistical.result result should handle no results",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should output the expected query and results",
      "fullTitle": "termsStats termsStats.result result should output the expected query and results",
      "duration": 2,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect a value",
      "fullTitle": "text text.hasValue should detect a value",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect if values is empty",
      "fullTitle": "text text.hasValue should detect if values is empty",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect if values only contains an empty string",
      "fullTitle": "text text.hasValue should detect if values only contains an empty string",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect if value is the empty string",
      "fullTitle": "text text.hasValue should detect if value is the empty string",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should check for values",
      "fullTitle": "text text.filter should check for values",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    }
  ],
  "pending": [],
  "failures": [],
  "passes": [
    {
      "title": "should check for values",
      "fullTitle": "date date.hasValue should check for values",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "basic",
      "fullTitle": "date date.filter basic",
      "duration": 3,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "basic datemath",
      "fullTitle": "date date.filter basic datemath",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "ms timestamp",
      "fullTitle": "date date.filter ms timestamp",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "unix timestamp",
      "fullTitle": "date date.filter unix timestamp",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should output the expected query and results",
      "fullTitle": "dateHistogram dateHistogram.result result should output the expected query and results",
      "duration": 11,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "If a value is provided, use $and",
      "fullTitle": "exists exists.filter If a value is provided, use $and",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "If no value is provided, use $or",
      "fullTitle": "exists exists.filter If no value is provided, use $or",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should allow nodes with values",
      "fullTitle": "facet facet.hasValue Should allow nodes with values",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should not allow nodes with values",
      "fullTitle": "facet facet.hasValue Should not allow nodes with values",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should call the search function and wait for it",
      "fullTitle": "facet facet.result should call the search function and wait for it",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should default the limit query to 10 if size is not provided",
      "fullTitle": "facet facet.result should default the limit query to 10 if size is not provided",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should allow unlimited queries",
      "fullTitle": "facet facet.result should allow unlimited queries",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should support optionsFilter",
      "fullTitle": "facet facet.result should support optionsFilter",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should support optionsFilter with multiple words and spaces",
      "fullTitle": "facet facet.result should support optionsFilter with multiple words and spaces",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should support isMongoId",
      "fullTitle": "facet facet.result should support isMongoId",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should check for value",
      "fullTitle": "mongoId mongoId.hasValue should check for value",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should create filter for _id",
      "fullTitle": "mongoId mongoId.filter should create filter for _id",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should handle $in with a data.values array",
      "fullTitle": "mongoId mongoId.filter should handle $in with a data.values array",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should handle $in with a data.values array",
      "fullTitle": "mongoId mongoId.filter should handle $in with a data.values array",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Allows optionally either min or max",
      "fullTitle": "number number.hasValue Allows optionally either min or max",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Allows 0 on min and max",
      "fullTitle": "number number.hasValue Allows 0 on min and max",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should reject empty string, null, undefined, Infinity, and NaN",
      "fullTitle": "number number.hasValue Should reject empty string, null, undefined, Infinity, and NaN",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should handle numbers as strings",
      "fullTitle": "number number.hasValue Should handle numbers as strings",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should convert both min and max to valid numbers",
      "fullTitle": "number number.filter Should convert both min and max to valid numbers",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should remove unused properties",
      "fullTitle": "number number.filter Should remove unused properties",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "Should remove fields if not valid",
      "fullTitle": "number number.filter Should remove fields if not valid",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should translate populate object into an array of $lookup objects",
      "fullTitle": "results convertPopulate should translate populate object into an array of $lookup objects",
      "duration": 6,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should add \"$unwind\" stage if \"unwind\" is present in the populate config",
      "fullTitle": "results convertPopulate should add \"$unwind\" stage if \"unwind\" is present in the populate config",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should return 0 if page is 1",
      "fullTitle": "results getStartRecord should return 0 if page is 1",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should return 0 if page is < 1",
      "fullTitle": "results getStartRecord should return 0 if page is < 1",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should return 10 if page is 2",
      "fullTitle": "results getStartRecord should return 10 if page is 2",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should put $sort, $skip, $limit first in pipeline",
      "fullTitle": "results getResultsQuery should put $sort, $skip, $limit first in pipeline",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should put $sort, $skip, $limit first in pipeline where sort field is not part of a join",
      "fullTitle": "results getResultsQuery should put $sort, $skip, $limit first in pipeline where sort field is not part of a join",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should put $sort, $skip, $limit first after $lookup",
      "fullTitle": "results getResultsQuery should put $sort, $skip, $limit first after $lookup",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should sort descending and skip $lookup and $project",
      "fullTitle": "results getResultsQuery should sort descending and skip $lookup and $project",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should not have $limit stage if pageSize is 0",
      "fullTitle": "results getResultsQuery should not have $limit stage if pageSize is 0",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should not have $sort stage if sortField is missing",
      "fullTitle": "results getResultsQuery should not have $sort stage if sortField is missing",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should fetch an extra item if skipCount is true",
      "fullTitle": "results getResultsQuery should fetch an extra item if skipCount is true",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should remove redundant child paths",
      "fullTitle": "results projectFromInclude should remove redundant child paths",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should only set hasMore if count is skipped",
      "fullTitle": "results getResponse should only set hasMore if count is skipped",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should set hasMore if there are extra results",
      "fullTitle": "results getResponse should set hasMore if there are extra results",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should not set hasMore if there are no extra results",
      "fullTitle": "results getResponse should not set hasMore if there are no extra results",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should set startRecord and endRecord based on the page",
      "fullTitle": "results getResponse should set startRecord and endRecord based on the page",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should set totalRecords based on the count (if it exists)",
      "fullTitle": "results getResponse should set totalRecords based on the count (if it exists)",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should output the expected query",
      "fullTitle": "statistical statistical.result result should output the expected query",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should handle no results",
      "fullTitle": "statistical statistical.result result should handle no results",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "result should output the expected query and results",
      "fullTitle": "termsStats termsStats.result result should output the expected query and results",
      "duration": 2,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect a value",
      "fullTitle": "text text.hasValue should detect a value",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect if values is empty",
      "fullTitle": "text text.hasValue should detect if values is empty",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect if values only contains an empty string",
      "fullTitle": "text text.hasValue should detect if values only contains an empty string",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should detect if value is the empty string",
      "fullTitle": "text text.hasValue should detect if value is the empty string",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "should check for values",
      "fullTitle": "text text.filter should check for values",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    }
  ]
}
    at /home/circleci/project/node_modules/duti/src/utils.js:37:11
    at <anonymous>
```
### Dangerfile
```
15| 
16| schedule(async () => {
17|   let dutiConfig
18|   try {
19|     let { config } = await explorer.load(process.cwd())
---------------------------------------------------------^
20|     dutiConfig = config
21|   } catch (e) {
22|     dutiConfig = defaultConfig
23|   }
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5ce9042533e393eae730fdb9c55d9707aeaeef63
</p>

**Comment by doug-patterson** [comment]
@daedalus28 I assert that mingo is broken. $project with $size works fine in regular mongo and gets you the size back -- here with mingo it converts your array into an equal-sized array of empty objects.

I consider this fixed now unless you tell me specifically what's wrong.

I will now restore testing of the timezone-sensitive props.

**Comment by doug-patterson** [comment]
@dubiousdavid since Sam modeled this on code of yours from a marketplace report you may be able to help out.

Also, if anyone knows anything about why mingo $project: { $size } doesn't work please do let me know

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>This PR has failing tests. Please alleviate the errors and commit them

<details>
  <summary>result should output the expected query and results</summary>
  <code>expected { Object (entries) } to deeply equal { Object (entries) }</code>
</details></td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>The changelog has not been updated. Please update the changelog.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>The version was not updated. Please update the version.</td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7e0c6b5969da303ab42871df74cef9f6138f24d9
</p>

**Comment by doug-patterson** [comment]
ok, tests are still failing on the timezone sensitive props. in progress on that...

**Comment by doug-patterson** [comment]
just need to make the tests still pass locally and we're good...

File: test/example-types/dateHistogram.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ let aggregate = sampleData => aggs => new mingo.Aggregator(aggs).run(sampleData)
 let hoursOffset = new Date().getTimezoneOffset() / 60
 let utcDate = x => {
   var d = new Date(x)
-  d.setHours(d.getHours() + hoursOffset)
+  d.setHours(d.getHours() + hoursOffset * 2)
```
Comment (dubiousdavid) [inline test/example-types/dateHistogram.js:13]: Can you add the note from the PR description here? This is a little weird.

**Comment by doug-patterson** [comment]
@dubiousdavid @daedalus28 updated, ready for review.

**Comment by doug-patterson** [comment]
@dubiousdavid bump

**Comment by dubiousdavid** [comment]
I'm wondering if Mingo is a good choice for this repo. The workarounds in the test seem less than ideal. Maybe we should consider `mongodb-memory-server`.

**Comment by doug-patterson** [comment]
@dubiousdavid @daedalus28 I'm not against the suggestion to replace mingo with something more conformant in the tests. It's used in the tests for three of the example types:

https://github.com/smartprocure/contexture-mongo/search?q=mingo&unscoped_q=mingo

Since I'd rather not drop the migration for this right now my preference is that we open a tech debt issue to upgrade from mingo in all three tests. Will do now if that's preferred, of course.

**Comment by dubiousdavid** [comment]
@doug-patterson I created this PR which cleans up the tests for this example type. https://github.com/smartprocure/contexture-mongo/pull/75

**Comment by doug-patterson** [comment]
@dubiousdavid @daedalus28 updated
